### PR TITLE
Made team lead schema and use case with TrackDevelopmentStatus id

### LINKED ISSUE #66: Make team lead schema
Your task is to make the schema with general possibilities that system allows to the teamlead.

### LINKED ISSUE #71: Make schema for 1 use case (4)
Your task is to make shema for use case with such id: **TrackDevelopmentStatus**

Prerequisites:

Image

### PR DESCRIPTION
**Pull request by kropli**
- added team lead schema
- added use case with TrackDevelopmentStatus id
- small text change in stakeholders-needs.md file
- small text change in General schema

closes #71, closes #66

### CODE REVIEW

**Comment by kropli** [comment]
image
image

**Comment by kropli** [comment]
image

**Comment by kropli** [comment]
image

**Comment by kropli** [comment]
image

**Comment by kropli** [comment]
image

**Comment by kropli** [comment]
image

**Review by Moriartymath — APPROVED** [review]

**Pull request merged**
